[package]
name = "diru"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "diru"
path = "src/bin/diru/main.rs"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
anyhow = "1.0"
humansize = "2.1.3"
walkdir = "2.5.0"
jwalk = "0.8.1"
